name: CI

on:
  push:
    branches:
      - master

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        # The normal requirements.txt is installed as it provides files for mypy to use.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (Pylint)
        run: pylint --rcfile=setup.cfg ./discordhealthcheck

      - name: Lint (Flake8)
        run: flake8 ./discordhealthcheck

      - name: Type analysis (MyPy)
        run: mypy ./discordhealthcheck

      - name: Security analysis (Bandit)
        run: bandit -r ./discordhealthcheck
